### ISSUE TITLE
Non-functional requirements

### ISSUE THREAD

**Issue by sljur** [sljur/Super_Scouts#12]
Make a numbered list of non-functional requirements that are important for your software. Explain their importance. Follow the terminology of ISO/IEC 25010:2011. For each non-functional requirement, give an objective goal/measurement in order to provide verifiability for the requirement. You can find more details at the following URL:
[https://ieeexplore.ieee.org/document/8559686Links to an external site.](https://ieeexplore.ieee.org/document/8559686)

Grading criteria (2 points): Follow the ISO-IEC terminology, explain why they are important, provide verifiability criteria for each requirement.

**Comment by BeatrizO** [comment]
Completed.
