### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by sljur** [sljur/Super_Scouts#13]
What will be your MVP? Which features are you going to validate? How?

Grading criteria (2 points): Describe what would be considered the Minimal Viable Product and how it will be tested (e.g., via implementation, prototyping, Wizard of Woz, etc.). Make clear what you are going to validate. The MVP should be coherent with the previous sections.

**Comment by LotsoPopcorn12** [comment]
Completed and finalized in deliverable 2
