### ISSUE TITLE
Product Position Statement 

### ISSUE THREAD

**Issue by BeatrizO** [sljur/Super_Scouts#30]
A product position statement communicates the intent of the application and the importance of the project to all concerned personnel. The product should mitigate the aforementioned problem. Provide a statement according to the following structure:

For
[target customer]
Who
[statement of the need or opportunity]
The (product name)
[product name] is a [product category]
That
[statement of key benefit; that is, the compelling reason to buy]
Unlike
[primary competitive alternative]
Our product
[statement of primary differentiation]

Example of a product position statement: “For college students who have many parallel homework assignments, MyPrioritizationApp is a planning app that crowdsources the identification of complexity and time necessary to accomplish assignments, supporting the informed prioritization; unlike myHomework Student Planner, our product does not rely on the judgment of a student who hasn’t started the homework yet.” Make sure your product position statement is related to your problem.

**Comment by sljur** [comment]
I added our product position statement into our Deliverable 2.
