### ISSUE TITLE
Product Position Statement:

### ISSUE THREAD

**Issue by sljur** [sljur/Super_Scouts#8]
A product position statement communicates the intent of the application and the importance of the project to all concerned personnel. The product should mitigate the aforementioned problem. Provide a statement according to the following structure:

For
[target customer]
Who
[statement of the need or opportunity]
The (product name)
[product name] is a [product category]
That
[statement of key benefit; that is, the compelling reason to buy]
Unlike
[primary competitive alternative]
Our product
[statement of primary differentiation]

**Comment by patriciakmadrid** [comment]
For
[The Users]
Who
[desire to have all the information about their organization in one place]
The
[Super Scout Website] is a [organizational website]
That
[Keeps all of the organization's day-to-day workings in the same location]
Unlike
[ScoutBook;BAND;Discord;TeamSnap;Facebook Messenger;Email]
Our product
[has a streamlined approach to activity planning for organizations]
