### ISSUE TITLE
Value proposition and customer segment

### ISSUE THREAD

**Issue by sljur** [sljur/Super_Scouts#9]
Report the value propositions and customer segments of your product. Make sure that your value proposition is coherent with the product position statement and contains the following elements: i) what your product is; ii) the target customer; iii) the value your product provides; and iv) why your product is unique.

Example:
Value proposition: MyPrioritizationApp is a crowdsourced planning app {(i) what your product is} that allows college students {(ii) target costumer} to make better use of their time {(iii) the value your product provides}, prioritizing homework based on more accurate information of required time and complexity of the assignments {(iv) why your product is unique}.”
Consumer segment: College students who have many parallel homework assignments

**Comment by BeatrizO** [comment]
Completed.
